apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apihub-system

resources:
  - ../../base/namespaces/namespaces.yaml
  - ../../services/api-registry/configmap.yaml
  - ../../services/api-registry/deployment.yaml
  - ../../services/dispatcher/configmap.yaml
  - ../../services/dispatcher/deployment.yaml
  - ../../services/auth/configmap.yaml
  - ../../services/auth/deployment.yaml
  - ../../services/executor/configmap.yaml
  - ../../services/executor/deployment.yaml

patches:
  - target:
      kind: Deployment
      name: api-registry
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: dispatcher
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: auth
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: executor
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
