- op: add
  path: /spec/template/spec/containers/0/envFrom/-
  value:
    configMapRef:
      name: apihub-shared-infra-prod
- op: add
  path: /spec/template/spec/containers/0/envFrom/-
  value:
    secretRef:
      name: apihub-shared-secret-prod
