apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-config
  namespace: apihub-system
  labels:
    app.kubernetes.io/name: billing
    app.kubernetes.io/part-of: apihub
data:
  APP_NAME: billing
  ENV: dev
  LOG_LEVEL: INFO
  PG_HOST: apihub-rds.internal
  PG_PORT: "5432"
  PG_DATABASE: apihub
  PG_POOL_MIN: "2"
  PG_POOL_MAX: "10"
  CH_HOST: apihub-ch.internal
  CH_PORT: "8123"
  CH_USERNAME: apihub
  CH_DATABASE: apihub
  CH_POOL_SIZE: "10"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.apihub-monitoring:4317
  OTEL_SERVICE_NAME: billing
  OTEL_RESOURCE_ATTRIBUTES: deployment.environment=dev
---
apiVersion: v1
kind: Secret
metadata:
  name: billing-secret
  namespace: apihub-system
type: Opaque
# stringData:
#   PG_PASSWORD: ...
#   CH_PASSWORD: ...
