apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apihub-system

resources:
  - ../../base/namespaces/namespaces.yaml
  - ../../services/api-registry/configmap.yaml
  - ../../services/api-registry/deployment.yaml
  - ../../services/dispatcher/configmap.yaml
  - ../../services/dispatcher/deployment.yaml

patches:
  - target:
      kind: Deployment
      name: api-registry
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 4000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 4Gi
  - target:
      kind: Deployment
      name: dispatcher
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 8
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 4000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 4Gi

# prod 走 Rollout（Argo Rollouts canary），见 docs/09-deployment.md §6.3
